#!/usr/bin/env node
/**
 * doclint.mjs — mechanical checks on the documentation.
 *
 * Docs rot silently. Nothing fails when a path stops existing or a count goes
 * out of date, so the drift is only found by a human who happens to read that
 * line — and then it has usually been wrong for months.
 *
 * The checks here are the ones this repository has actually needed:
 *
 *   PATHS. Every repo-relative path mentioned in a .md must exist. Deleting a
 *   file used to leave dangling references behind in four documents at once.
 *
 *   COUNTS. Prose must not state a number the repo can count itself. Fixture and
 *   document counts drifted three times in a single working session (11/51 ->
 *   16/65 -> 18/73), each time silently wrong until someone re-derived it.
 *
 *   SPEC CITATIONS. A comment saying "(SPEC.md §3.1)" is only useful while §3.1
 *   means what it did when someone wrote it. Renumbering the spec breaks every
 *   citation at once, silently, and a stale one is worse than none: it sends a
 *   reader to a rule that now says something else. Eight such citations survived
 *   a spec rewrite here, pointing at section numbers that no longer existed.
 *
 * Usage: node scripts/doclint.mjs
 */
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const problems = [];

function markdownFiles(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    // `ledger/` is tool-managed: AGENTS.md and ledger.html are GENERATED by
    // cs-ledger and must never be hand-edited (upgrade rewrites them). Its
    // manual correctly cites paths in the ledger tool's own repo, which do not
    // exist here by design — target repos deliberately carry no schema copy.
    if (["node_modules", ".git", "oracle", "bin", "ledger"].includes(entry.name)) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) markdownFiles(full, out);
    else if (entry.name.endsWith(".md")) out.push(full);
  }
  return out;
}

// A token looks like a repo path when it contains a slash and starts with a
// known top-level directory or a known root file. Deliberately conservative:
// URLs, prose containing slashes, and paths inside fenced example commands that
// refer to the USER's machine must not be flagged.
const ROOTS = new Set(readdirSync(ROOT).filter((n) => !n.startsWith(".")));
function looksLikeRepoPath(token) {
  const head = token.split("/")[0];
  return token.includes("/") && ROOTS.has(head) && !token.startsWith("http");
}

for (const file of markdownFiles(ROOT)) {
  const rel = file.slice(ROOT.length + 1);
  const text = readFileSync(file, "utf8");

  // --- paths -------------------------------------------------------------
  // Only inside backticks: prose mentions shapes like `<dir>/summary.json` that
  // are patterns, not paths, and those carry angle brackets or globs.
  for (const [, token] of text.matchAll(/`([^`\n]+)`/g)) {
    // A backticked span is often a COMMAND (`script.sh --verify`); only its
    // first word can be a path.
    const cleaned = token.trim().split(/\s+/)[0].replace(/[.,;:)]+$/, "");
    if (!looksLikeRepoPath(cleaned)) continue;
    if (/[<>*{}|]/.test(cleaned)) continue;            // a pattern, not a path
    if (cleaned.includes("://")) continue;
    // Go symbol references share the shape of a path: `internal/cli.version` is
    // package.identifier, not a file. Treat a dotted final segment as a path
    // only when the suffix is a real file extension.
    const last = cleaned.split("/").pop();
    if (last.includes(".")) {
      const ext = last.split(".").pop().toLowerCase();
      const FILE_EXTS = new Set(["md","json","mjs","js","ts","tsx","go","sh","yaml","yml","html","css","txt","lock","png","jsonl"]);
      if (!FILE_EXTS.has(ext)) continue;
    }
    const target = join(ROOT, cleaned.split("#")[0]);
    if (!existsSync(target)) problems.push(`${rel}: references a path that does not exist: ${cleaned}`);
  }

  // --- counts ------------------------------------------------------------
  // Numbers next to things the repo can count. The gates report these; prose
  // that repeats them goes stale the moment the corpus changes.
  const countable = /\b(\d{1,4})\s+(fixtures?|fixture directories|directories of real sessions|oracle documents|documents|sessions|goldens|baselines)\b/gi;
  for (const [match, , noun] of text.matchAll(countable)) {
    // A count OF something in an example command's output is fine; a count in
    // prose is the problem. Fenced blocks are excluded below.
    const idx = text.indexOf(match);
    const before = text.slice(0, idx);
    const fences = (before.match(/```/g) || []).length;
    if (fences % 2 === 1) continue;                    // inside a fenced block
    problems.push(`${rel}: states a count the gates already report ("${match.trim()}") — let ${noun} be counted, not asserted`);
  }
}

// --- the embedded manual must match the file -------------------------------
// `cs-tracer manual` prints an embedded copy of MANUAL.md. If the binary is
// stale the two disagree, and the version a user reads is the wrong one.
const manualPath = join(ROOT, "MANUAL.md");
const binary = join(ROOT, "bin", "cs-tracer");
if (existsSync(binary) && existsSync(manualPath)) {
  const { execFileSync } = await import("node:child_process");
  const printed = execFileSync(binary, ["manual"], { encoding: "utf8" });
  if (printed !== readFileSync(manualPath, "utf8")) {
    problems.push("bin/cs-tracer manual does not match MANUAL.md — rebuild (make build)");
  }
}

// --- the manual must document every flag the parser accepts ----------------
const cliSource = join(ROOT, "internal", "cli", "cli.go");
if (existsSync(cliSource) && existsSync(manualPath)) {
  const manual = readFileSync(manualPath, "utf8");
  const source = readFileSync(cliSource, "utf8");
  const parseBlock = source.slice(source.indexOf("func parseArgs"), source.indexOf("func flagValue"));
  const flags = new Set();
  for (const [, flag] of parseBlock.matchAll(/case ((?:"--?[a-z-]+"(?:, )?)+):/g)) {
    for (const [, name] of flag.matchAll(/"(--?[a-z-]+)"/g)) flags.add(name);
  }
  for (const flag of flags) {
    if (flag === "-h" || flag === "--help" || flag === "--version") continue; // covered by --help
    if (!manual.includes(flag)) problems.push(`MANUAL.md does not document ${flag}, which the parser accepts`);
  }
}

// --- every §N cited in source must exist in SPEC.md -------------------------
//
// Cheap to check, and it fails the moment the spec is renumbered rather than
// months later when a reader follows a citation into the wrong rule.
const specText = readFileSync(join(ROOT, "SPEC.md"), "utf8");
const specSections = new Set();
for (const m of specText.matchAll(/^## (\d+)\./gm)) specSections.add(m[1]);
for (const m of specText.matchAll(/^\*\*(\d+\.\d+)/gm)) specSections.add(m[1]);

function sourceFiles(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (["node_modules", ".git", "oracle", "bin", "ledger", "dist"].includes(entry.name)) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) sourceFiles(full, out);
    else if (/\.(go|mjs|ts|tsx|md|sh)$/.test(entry.name)) out.push(full);
  }
  return out;
}

for (const file of sourceFiles(ROOT)) {
  const text = readFileSync(file, "utf8");
  for (const m of text.matchAll(/§(\d+(?:\.\d+)*)/g)) {
    if (specSections.has(m[1])) continue;
    const line = text.slice(0, m.index).split("\n").length;
    problems.push(`${file.slice(ROOT.length + 1)}:${line}: cites §${m[1]}, which is not a section of SPEC.md`);
  }
}

if (problems.length) {
  console.error("doclint FAILED:");
  for (const p of problems) console.error(`  ${p}`);
  process.exit(1);
}
console.log("doclint: docs reference only real paths, assert no countable numbers, every \u00a7 citation resolves, and the manual matches the binary");

