#!/usr/bin/env bash
#
# Regenerate oracle/ — the expected output every gate compares against.
#
# The work happens in Go (internal/cli/golden_test.go), which is also where the
# gates read the goldens back, so the generator and the gate share one definition
# of the format instead of two that can drift apart. This script is the interface:
# it is what CONTRIBUTING.md names, and it keeps the warning attached to the act.
#
# No build step is needed — the viewer assets are committed and embedded at
# compile time, so this works from a fresh clone.
#
# THIS IS A DELIBERATE ACT, AND IT IS WEAKER THAN IT LOOKS.
#
# These goldens are generated by the tool they test, so running this script can
# make ANY gate pass. It cannot tell you the output is correct — only that it is
# what cs-tracer currently produces. The review of the resulting diff is the
# check; see CONTRIBUTING.md's golden-update ritual.
#
# Usage:  scripts/gen-goldens.sh

set -euo pipefail
cd "$(dirname "$0")/.."

go test -v -count=1 ./internal/cli -run TestUpdateGoldens -update

echo
echo "  REVIEW THE DIFF — nothing external verified this."
